import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { Providers } from "./provider";
import { LocaleProvider } from "@/contexts/LocaleContext";
import IntlProvider from "@/components/IntlProvider";

const publicSans = Public_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${publicSans.variable} antialiased bg-bg`}
      >
        <IntlProvider>
          <LocaleProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              disableTransitionOnChange
            >
              <Providers>{children}</Providers>
            </ThemeProvider>
          </LocaleProvider>
        </IntlProvider>
      </body>
    </html>
  );
}
