import type { Metadata } from "next";
import "./globals.css";
import { LocaleProvider } from "@/contexts/LocaleContext";
import IntlProvider from "@/components/IntlProvider";
import { publicSans } from "./fonts";
import { Header } from "@/components/header";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={`${publicSans.variable} antialiased bg-bg`}>
        <LocaleProvider>
          <IntlProvider>
              <Header />
              <main>{children}</main>
              <Footer />
          </IntlProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
